### ISSUE TITLE
@noupdate::set is no longer recognized by Skript

### ISSUE THREAD

**Issue by crazedorangutan** [SkQuery/SkQuery#100]
I found this effect on the docs (https://skripthub.net/docs/?id=3901) and used the example given, Skript didn't recognize it, so I tried adding player to the example but it still wouldn't work, so I assume this is something that broke with Skript updating to 2.6.1

- Skript version: 2.6.1
- Server software: Paper
- Server version: 1.16.5

A fix for this soon would be greatly appreciated, as this is a fairly important part of my minigame

**Comment by TheLimeGlass** [comment]
That example assumes you have an entity in the event, you may not have an entity wherever you used it.

`@noupdate::set block at location of player to stone` is an example.

**Comment by crazedorangutan** [comment]
Same error:
![image](https://user-images.githubusercontent.com/95040748/157757631-3da34896-9adf-45f9-83b8-ae97ff649ac7.png)

**Comment by TheLimeGlass** [comment]
syntax aliases added to support latest Skript you can use `set block at location of player to stone with no updates` in 4.1.10
