### ISSUE TITLE
Developer Mode Message

### ISSUE THREAD

**Issue by ImNotStable** [SkQuery/SkQuery#105]
Could you add an extra script option to set it if you get the reload message when a script is automatically reloaded with Developer Options

I'm not sure how the options themselves work or if it'd be a difficult task but I'm asking for an option such as
`
$ developer mode message true/false|on/off
`

**Comment by TheLimeGlass** [comment]
To disable the reload messages? I don't think this is a good idea.

**Comment by ImNotStable** [comment]
Why wouldn't it be
