### ISSUE TITLE
SkQuery Permissions not working

### ISSUE THREAD

**Issue by Fyriiee** [SkQuery/SkQuery#116]
**Describe the bug**

SkQuery Permissions not working
![image](https://user-images.githubusercontent.com/58646005/180364877-0a8546de-1ec0-4676-be02-76e59328f5f5.png)

**Information:**
- Skript version: 2.6.3
- Server software: Paper
- Server version: 1.18.2

- Skript addons: skript-yaml v1.4, SkQuery v4.1.7, SkBee v1.17.0

**Additional context**

![image](https://user-images.githubusercontent.com/58646005/180365214-834eb283-6058-4725-907d-e6e9569e51b2.png)
So I saw "Fixed the permission manager" in the SkQuery changelog, so I tried making a Skript with it. Is this behavior a bug or intentional?

**Comment by TheLimeGlass** [comment]
Permissions were removed, they're in vanilla Skript now.
