### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by Elliot125** [SkQuery/SkQuery#124]
**Describe the bug**
I'm using a 1.8 server, and want to use Skquery but when I try it, I keep getting errors.

**To Reproduce**
Steps to reproduce the behavior if there are any.

**Information:**
- Skript version: v2.2-dev36
- Server software: Paper 
- Server version: 1.8

**Comment by Elliot125** [comment]
![Screenshot 2022-11-12 164801](https://user-images.githubusercontent.com/118066603/201482312-2cbf2aaa-b74f-4cb3-86a0-e6693bd5b13f.png)

**Comment by TheLimeGlass** [comment]
1.8 is 9 years old. Thr latest version does not support 1.8. Use version 3.22+ from the Bukkit page https://dev.bukkit.org/projects/skquery
