### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by zikehalil3535** [SkQuery/SkQuery#139]
**Describe the bug**
Im getting error
**To Reproduce**
Steps to reproduce the behavior if there are any.
On server start Im getting error.
**Information:**
- Skript version: 2.6.3
- Server software: Purpur
- Server version: 1.19.3

**Additional context**
Add any other context about the bug here.
![image](https://user-images.githubusercontent.com/88826436/224689468-a27876f5-b011-4ad4-8d81-a8b27976d262.png)

**Comment by TheLimeGlass** [comment]
Fixed in 4.1.9
