### ISSUE TITLE
restore inventory is not working

### ISSUE THREAD

**Issue by GONJYY** [SkQuery/SkQuery#144]
**Describe the bug**
The restore inventory effect is not working and returning this error in the console 
`[13:45:15 ERROR]: #!#! java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 41)`

**To Reproduce**
The code I used:
`on right click holding a barrier:`
`    restore inventory of player from {inv::%player%}`

and the code I used to set the variable was: 
`set {inv::%player%} to player's serialized inventory`

**Information:**
- Skript version: 2.6.4
- Server software: Paper
- Server version: 1.19.2

**Additional context**
Screenshots:
![image](https://user-images.githubusercontent.com/130846899/232229140-0b73bfdd-7f8a-4c10-8eed-94d728480ab7.png)

![image](https://user-images.githubusercontent.com/130846899/232229148-b69fcf1c-89e2-42d4-87ff-3230b5071326.png)

**Comment by TheLimeGlass** [comment]
The inventory type was incorrect. You must use the same inventory that was involved in serialization. Placed warning in 4.1.10
