### ISSUE TITLE
Inventory click doesn't work

### ISSUE THREAD

**Issue by YellowZaki** [SkQuery/SkQuery#15]
**Describe the bug**
on inventory click doesn't work. Skript have the event by default and when I remove SkQuery, it works.

**Information:**
- Skript version: 2.4-alpha3
- Server software: Spigot
- Server version: 1.14.2

**Comment by Laukage** [comment]
isn't this related to #13 ?

**Comment by TheLimeGlass** [comment]
No error posting and probably related to #13

**Comment by YellowZaki** [comment]
@TheLimeGlass any exceptions on the console.
