### ISSUE TITLE
format slot to run [regularPage({_p}, 0)]

### ISSUE THREAD

**Issue by AlexTeal03** [SkQuery/SkQuery#154]
**Describe the bug**
I am in the process of upgrading all my scripts to 1.18. When a player clicks the slot formatted "to run [regularPage({_p}, 0)]" {_p} being the player, the regularPage function sees {_p} as none. 

**To Reproduce**
Code:
function titlesPage(p: player):
open chest with 1 rows named "&dTitles" to {_p}
format slot 3 of {_p} with name tag named "&d&nRegular Titles" with lore "&7Just your &nAverage&7 title!","&d&l* &fCommon &7titles","" and "&d&l(!) &dClick to view &nRegular&d Titles!" to run [regularPage({_p}, 0)]

function regularPage(p: player, page: number):
open chest with 6 rows named "&d&nRegular Titles" to {_p} 
**Information:**
- Skript version: 2.6.4
- Server software: Paper
- Server version: 1.19.4

**Additional context**
This code worked fine in 1.8 and doesn't show any errors.

**Comment by TheLimeGlass** [comment]
You have to format the inventory. use `format slot 3 of {_inventory}` not against the player, the player's inventory is different than the open inventory, like currently opened inventory
