### ISSUE TITLE
Syntax conflict of "size of"

### ISSUE THREAD

**Issue by aeonlamb** [SkQuery/SkQuery#16]
**Describe the bug**
The new worldborder expressions in 4.1.0 contains a "size of worldborder" expression. This conflicts with Skript's "size of" / "amount of" expression and causes errors.

**To Reproduce**
- Load Skript and SkQuery 4.1.0
- Enable a script that tries to get "size of" a list variable (skript's syntax)
- Error

**Information:**
- Skript version: 2.4-alpha4 (Also happens on 2.3.7)
- Server software: Paper
- Server version: 1.14.3 (Also happens on 1.13.2)

**Additional context**
This is unrelated but the plugin.yml version of skquery still says 3.6.5. That should probably be updated :stuck_out_tongue:

**Comment by TheLimeGlass** [comment]
Fixed in 4.1.1
