### ISSUE TITLE
Feature Request: Trail projectiles

### ISSUE THREAD

**Issue by bloggy** [SkQuery/SkQuery#28]
Hi there,
in the past there was a "trail projectile" effect for having particles on arrows. This was implemented in skQuery but actually does not work anymore. Could you fix this? It's way to quicker to script this thing and instead have only 1 line of code. Would be nice!

**Comment by TheLimeGlass** [comment]
It already exists 

trail projectile with %particles%

**Comment by bloggy** [comment]
It does not work for me. Could you post an example?
