### ISSUE TITLE
Fix minecart push.

### ISSUE THREAD

**Issue by Misio12320** [SkQuery/SkQuery#29]
**Describe the bug**
I want to create when player enter a region with minecart: it should push him up with it but does not work..
+ Suggestion. Add 
rightclick:
    make clicked block powered
**To Reproduce**
Write code
on enter region "wow":
    send name of player's vehicle
    push player's vehicle upwards with speed 5.0
and does not work.
**Information:**
- Skript version: 2.5-pre1
- Server software: Spigot
- Server version: 1.15.2

**Additional context**
Add any other context about the bug here.

**Comment by TheLimeGlass** [comment]
This is Skript not SkQuery

**Comment by Misio12320** [comment]
What about the suggestion? Add "make %entity% powered" I mean powered rail

**Comment by TheLimeGlass** [comment]
It's already a thing in Skript https://skripthub.net/docs/?id=1137
