### ISSUE TITLE
Colored Armor in GUIs

### ISSUE THREAD

**Issue by GoldySlime** [SkQuery/SkQuery#30]
Hey, I think after the new update of the new SKQuery we cannot use the Colored Armor for the GUI. Is it just me or it is really gone?

`format slot 10 of player with leather helmet dyed black named "&fBoar's Leather Hood" with lore "&7Armor" and "" and "&7Armor: +2" and "&7Toughness: +2.5" to be unstealable`
This was my code and it work just fine, but now there is no error when I reload the skript, but it doesn't show anything after that line.

Thanks

**Comment by TheLimeGlass** [comment]
It's Skript https://skripthub.net/docs/?id=4013
