### ISSUE TITLE
SkQuery 4.1.2

### ISSUE THREAD

**Issue by dodisek17** [SkQuery/SkQuery#32]
**Describe the bug**
Hi, I'm using your plugin but there is a big problem... Plugin is reporting error "Is it up to date?" but I have the newest version.. .I'm using version 4.1.2 but plugin is reporting that:
18:24:01[ERROR] Error occurred while enabling SkQuery v3.6.5 (Is it up to date?)
at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:30) ~[?:?]

I'll be glad for your response.

**Information:**
- Skript version: 4.1.2
- Server software: Spigot
- Server version: 1.8

**Comment by TheLimeGlass** [comment]
We need the full error, that is not the full error.

**Comment by Louuuwh** [comment]
I've the same problem without error.
My jar of SkQuery is 4.1.2 but in console when I start my server :
[SkQuery] Loading SkQuery v3.6.5
