### ISSUE TITLE
Minecart push

### ISSUE THREAD

**Issue by Misio12320** [SkQuery/SkQuery#33]
**Describe the bug**
The minecart push does not work, but horse works.

**To Reproduce**
write code `on enter region "":
                      push player's vehicle upwards with speed x `

**Information:**
- Skript version: 2.5-pre2
- Server software: Paper
- Server version: 1.15.2

**Additional context**
none

**Comment by TheLimeGlass** [comment]
This is a Skript effect not SkQuery.
