### ISSUE TITLE
Map Support

### ISSUE THREAD

**Issue by dowen01** [SkQuery/SkQuery#36]
Good Afternoon

Is there any chance of fixing the "Removed broken map support." I use it so much and can't seem to find any other way of doing it :(

Please please

**Comment by TheLimeGlass** [comment]
Skellett has map support

**Comment by dowen01** [comment]
I have tried Skellett but I cant load images to map IDs (If I am being dumb please tell me) With the SkQuery map support it was perfect, you just pointed the image at a map ID job done! Really miss this.

Either way thanks for replying
