### ISSUE TITLE
Problem with "HttpURLConnection"

### ISSUE THREAD

**Issue by Carvane** [SkQuery/SkQuery#37]
Description: sometimes the server does not respond and crashes by the script

Steps to Reproduce: when the player connects to the server and the script checks the page
Skript: https://pastebin.com/n2YNwkbX

Errors / Screenshots: https://pastebin.com/bdDEu6wn

Server Information:

**Server version/platform: Tuinity 1.15.2 Build #33
**Skript version: 2.5-alpha3
**Skquery version: 4.1.2

**Comment by TheLimeGlass** [comment]
Use $ thread above the link syntax that uses the URL, also whatever website you are using timed out.
