### ISSUE TITLE
Get block or entity hit in "On Item Projectile hit"

### ISSUE THREAD

**Issue by Katalijst** [SkQuery/SkQuery#38]
Hello,
Is it possible to add an expression to get the entity which was hit in an "On Item Projectile hit" event ?
It would be really useful !

**Comment by TheLimeGlass** [comment]
Yes use event-livingentity https://skripthub.net/docs/?id=3865

**Comment by Katalijst** [comment]
Well, event-living entity return the sender to me not the entity which was hit
