### ISSUE TITLE
Custom Crafting Recipes

### ISSUE THREAD

**Issue by ThatOneN00b** [SkQuery/SkQuery#41]
When making custom crafting recipes, you cannot use named items. I dont think this is the biggest bug of all time but its something i think would be great.

**Comment by ThatOneN00b** [comment]
Sorry, I realise this in unclear now! Here is what i mean --
```
on load:
    set {_glowingemerald} to glowing emerald named "&5Glowing Emerald"
    register new shapeless recipe for diamond chestplate using {_glowingemerald}, {_glowingemerald}, {_glowingemerald}, {_glowingemerald}, air, air, air, air, air
````
By doing this, you would assume that this means i can craft a chestplate only with the `{_glowingemerald}`, but you can use normal, unnamed emeralds.

**Comment by TheLimeGlass** [comment]
https://github.com/SkQuery/SkQuery/issues/5
