### ISSUE TITLE
Paper 1.15.2 crash

### ISSUE THREAD

**Issue by ShazadSkriptREPO** [SkQuery/SkQuery#44]
**Describe the bug**
SkQuery wont load in to my server.

**To Reproduce**
Paper Spigot 1.15.2 build #304

**Information:**
- Latest Skript Version
- Server software: Paper Spigot
- Server version: 1.15.2

**Additional context**
CONSOLE LOG:

https://pastebin.com/CCpPHaXA

**Comment by TheLimeGlass** [comment]
You have a modified plugin.yml of SkQuery, please make sure you're compiling the plugin properly, or downloading it from the official page https://www.spigotmc.org/resources/skquery-1-9-1-15.36631/
