### ISSUE TITLE
U R L Text expression cannot pull contents of .txt files over URL, only HTML.

### ISSUE THREAD

**Issue by andrewleppala** [SkQuery/SkQuery#48]
**Describe the bug**
URL Text expression cannot pull contents of .txt file and do anything with them, it will only show the contents of an HTML document.

**To Reproduce**
Run the following:
`set {_var} to text from https://example.com/stuff.txt`
`message "%{_var}%" to player`

**Information:**
- Skript version: 2.4.1
- Server software: PaperSpigot 1.12.2-R0.1-SNAPSHOT build 1618
- Server version: 1.12.2

**Additional context**
The contents of the new variable created is `<none>`. If running it against a raw pastebin link such as `https://pastebin.com/raw/fuyUJW53` the results are returned just fine.

**Comment by ImNotStable** [comment]
Honestly should be closed the difference is raw text look at both source pages
view-source:https://example.com/stuff.txt
view-source:https://pastebin.com/raw/fuyUJW53
