### ISSUE TITLE
cannot launch skquery

### ISSUE THREAD

**Issue by Qfrijters** [SkQuery/SkQuery#49]
**Describe the bug**
Errors at startup, also incorrect display of version

**To Reproduce**
literally startup the server

**Information:**
- Skript version:  2.5-alpha6
- Server software: paper
- Server version: 1.16 build#116

**Additional context**
pastebin with how it startup and then shuts down 
https://pastebin.com/UMPepQNy

**Comment by TheLimeGlass** [comment]
Fixed in 4.1.3
