### ISSUE TITLE
Skquery after 4.1.1 to 4.1.3 tps drops

### ISSUE THREAD

**Issue by waiching514** [SkQuery/SkQuery#51]
**Describe the bug**
When I upgrade Skquery 4.1.1 to 4.1.3 will make tps drop, It cause entitydamageevent and playerintractevent lag
using 4.1.3:
https://timings.aikar.co/?id=50470732f320489a82b706e43785d336
using 4.1.1:
https://timings.aikar.co/?id=b1f0341381d64ea6a0e217964738253f

Also, when the script having play sound make loading script so long
**To Reproduce**
server just upgrade 4.1.3 cause tps drops

**Information:**
- Skript version: 2.4.1
- Server software: paper
- Server version: 1.16.1-135

**Comment by TheLimeGlass** [comment]
There is nothing in SkQuery that causes lag, it's a library for scripts, and nothing from 4.1.1 to 4.1.3 has been changed or added to do so.
