### ISSUE TITLE
1.16.2 error on startup

### ISSUE THREAD

**Issue by Qfrijters** [SkQuery/SkQuery#52]
Goodmorning

SkQuery doesn't load since 1.16.2 update (understandable ;) )

`01.09 12:00:38 [Server] ERROR Could not load 'plugins/SkQuery-4.1.3.jar' in folder 'plugins'
01.09 12:00:38 [Server] INFO org.bukkit.plugin.UnknownDependencyException: Unknown dependency Skript. Please download and install Skript to run this plugin.
01.09 12:00:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.2.jar:git-Paper-173]
01.09 12:00:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[patched_1.16.2.jar:git-Paper-173]
01.09 12:00:38 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.2.jar:git-Paper-173]
01.09 12:00:38 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-173]
01.09 12:00:38 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-173]
01.09 12:00:38 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:?]`

kind regards
Quinten

**Comment by TheLimeGlass** [comment]
You need to have Skript installed on your server.
