### ISSUE TITLE
Push effect is delayed

### ISSUE THREAD

**Issue by Misio12320** [SkQuery/SkQuery#55]
Hey the push effect is delayed. When I was playing Minecraft at 1.15.2 and version of SkQuery 4.1.1 it was working fine the push was not delayed.
code:
`on enter region "void":
	push player upwards with speed 5.0
	cancel event
	wait 2.5 real seconds
	teleport player to location (-1.5), (66), (-1.5) in (world "void")`

[Skript] Server Version: git-Paper-211 (MC: 1.16.3)
[Skript] Skript Version: 2.5
[Skript] Installed Skript Addons:
[Skript] - Skent v1.9
[Skript] - SK-NBeeT v2.10.0 (https://github.com/ShaneBeee/Sk-NBeeT)
[Skript] - skUtilities v0.9.2 (https://tim740.github.io/)
[Skript] - SkQuery v4.1.3
[Skript] - SharpSK v1.6.3
Edit: 
The problem is when I jump into void the push does not work and I get more than 1 times teleported. Before when it worked fine I just got pushed and teleported 1 time which was good.

**Comment by TheLimeGlass** [comment]
Push effect is Skript not SkQuery
