### ISSUE TITLE
Issue with logs/leaves

### ISSUE THREAD

**Issue by Karrade** [SkQuery/SkQuery#58]
**Describe the bug**
Jungle leaves and/or jungle logs not recognized

**To Reproduce**
add the following and only oak leaves/logs will create, jungle leaves/logs will not
`register new shaped recipe for oak sapling using oak leaves, oak leaves, oak leaves, oak leaves, oak log, oak leaves, oak leaves, oak log, oak leaves`

`register new shaped recipe for jungle sapling using jungle leaves, jungle leaves, jungle leaves, jungle leaves, jungle log, jungle leaves, jungle leaves, jungle log, jungle leaves`

**Information:**
- Skript version: 2.5.1
- Server software: Spigot
- Server version: 1.16.4
- SkQuery version: 4.1.4

EDIT:
to compound on this `netherite ingot` does not work either as an ingredient

**Comment by TheLimeGlass** [comment]
https://github.com/SkQuery/SkQuery/issues/5
