### ISSUE TITLE
Bug Menu with SkQuery

### ISSUE THREAD

**Issue by Lennord** [SkQuery/SkQuery#64]
Hello, I found a problem to correct, when I create a menu and I'm creative and I open the menu and quit the menu quickly, it gives me an error and in addition it gives me the menu items (not everything and some items).

Here I wanted to tell you the problem by hoping that it will not be complicated to correct it...

Version Spigot: 1.16.4
Version Skript: 2.5.3
Version SkQuery: 4.1.4
List of plugins: Skript, SkQuery, Skungee, SkRayfall, SkBee and Skellett

Bug report: https://pastebin.com/UMCuatFf
Code: https://pastebin.com/SrUaGPND

**Comment by TheLimeGlass** [comment]
The error happens because you're formatting a slot that is greater than the inventory size.
