### ISSUE TITLE
NewUUID expression should be removed

### ISSUE THREAD

**Issue by ghost** [SkQuery/SkQuery#65]
**Describe the bug**
https://skriptlang.github.io/Skript/expressions.html#ExprRandomUUID is a thing now, so SkQuery should remove it from itself and SkQuery's syntax of it is also wrong, it works with "%uuid%" which sometimes causes conflicts when using syntax like "something of uuid of player"

**Information:**
- Skript version: 2.5.1
- Server software: Paper
- Server version: 1.12.2

**Comment by TheLimeGlass** [comment]
Removed in 4.1.6
