### ISSUE TITLE
The evaluate effect seems to cause some sort of memory leak

### ISSUE THREAD

**Issue by Mastriel** [SkQuery/SkQuery#67]
**Describe the bug**
When using evaluate with a function, and then reloading the file that function was defined in, it gives this error:
![image](https://user-images.githubusercontent.com/59402263/112920265-d6b3d980-90c5-11eb-8311-3911877149ab.png)
Each time you evaluate the function, you get another error like that.

**To Reproduce**
Run this code then reload the skript you wrote it in.
```vbs
function testFunc():
    broadcast "Hi"

command /test:
    trigger:
        evaluate "testFunc()"
```
This will happen as a result:
![image](https://user-images.githubusercontent.com/59402263/112920562-71141d00-90c6-11eb-9fd7-820015e159f1.png)

**Information:**
- Skript version: 2.5.3
- SkQuery version: 4.1.4
- Server software: Paper
- Server version: 1.16.5

**Additional context**
After reloading the skript, it seems to free up all of the memory from the leak.

**Comment by TheLimeGlass** [comment]
SkQuery would have nothing to do with this. Evaluate just parses an effect.

I also don't believe this is a memory leak either.

This issue is potentially related. https://github.com/SkriptLang/Skript/issues/2802

Are you sure your version is 2.5.3?
