### ISSUE TITLE
Worldborder's size syntax severe error

### ISSUE THREAD

**Issue by GallicoAquilae** [SkQuery/SkQuery#69]
**Describe the bug**
The syntax `(size|diameter) of world[ ]border[s] %worldborders% [over [a [(time|period) of]] %-timespan%]` makes a severe error

**To Reproduce**
I simply used the syntax as  set size of worldborder {_wb} to {_size} over 1 tick, I tried many ways, but none of them works.

**Information:**
- Skript version: 2.5.3
- Server software: git-Paper-520
- Server version: 1.16.5

**Additional context**
It was in a command event, I used temporary variables in the process that were set from a yaml value. In a debugging both world et size were set in the variables.

**Comment by TheLimeGlass** [comment]
I need the error

**Comment by DelayedGaming** [comment]
This issue is known to me, so I will be contributing to this issue.

Stacktrace: https://pastebin.com/uSw6a4km[https://pastebin.com/uSw6a4km]()

**Comment by TheLimeGlass** [comment]
Fixed in 4.1.6
