### ISSUE TITLE
Can not wipe individual items

### ISSUE THREAD

**Issue by danjo7** [SkQuery/SkQuery#70]
**Describe the bug**
can not wipe individual items

**To Reproduce**
on load:
    wipe crafting recipes for any diamond armor
    wipe crafting recipes for any diamond tools
    wipe crafting recipes for diamond sword
    wipe crafting recipes for enchantment table
    wipe crafting recipes for brewing stand
    wipe crafting recipes for magma cream

**Information:**
- Skript version: 4.1.4
- Server software: Spigot
- Server version: 1.12.2
- java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.CraftingManager.getInstance(). i assume this has to do with the crafting recipe manager.

**Additional context**
i can create recipes and "wipe server crafting recipes" works but wiping individual recipes like this doesnt work:
    wipe crafting recipes for any diamond armor
    wipe crafting recipes for any diamond tools
    wipe crafting recipes for diamond sword
    wipe crafting recipes for enchantment table
    wipe crafting recipes for brewing stand
    wipe crafting recipes for magma cream
this also gives no error
![image](https://user-images.githubusercontent.com/82383198/114390988-38307980-9b97-11eb-9bb1-9c27a9cb5a40.png)

**Comment by TheLimeGlass** [comment]
Crafting recipes were removed, please use any other addon that supports recipes like SkBee
