### ISSUE TITLE
Midi system does not play any drum-ish percussions.

### ISSUE THREAD

**Issue by xWestLC** [SkQuery/SkQuery#72]
**Describe the bug**
Even though I can clearly hear the percussions when converted into NBS or played by the Windows Media Player's lib, MidiParser event of .mid files does not include any percussions for some reason I don't know, and instead; plays them with only 'piano' notes or something else.

**To Reproduce**
Just type a small command that could play a midi file from a certain file location or from link, then try playing any .mid file that you are sure about it having percussions in it.
**Information:**
- Skript version: 2.5.3
- Server software: Paperspigot 1.16.5, build 651
- Server version: 1.16.5

**Comment by xWestLC** [comment]
bump?

**Comment by TheLimeGlass** [comment]
Because it sounds horrible.
