### ISSUE TITLE
player's scaled health expression bug

### ISSUE THREAD

**Issue by ghost** [SkQuery/SkQuery#74]
**Describe the bug**
when I set player's scaled health to 10 and use send "%player's scaled health%" it says 20. when I set it to 20, the expression says 40. it seems to use inconsistent numbers between SET operation and expression return
**To Reproduce**
Explained above

**Information:**
- Skript version: 2.5.1
- Server software: Purpur
- Server version: 1.16.5

**Comment by TheLimeGlass** [comment]
You have to set the health scaled mode to true before modification.

**Comment by GovindasOM** [comment]
nope, look: 
![2021-06-07 17;11](https://user-images.githubusercontent.com/16716020/121031807-37cced00-c79a-11eb-92af-83028e65ec77.png)

**Comment by TheLimeGlass** [comment]
SkQuery doubles the number that was set.

**Comment by GovindasOM** [comment]
I think it is self-explanatory that it is misleading behavior and it should be made the same
