### ISSUE TITLE
Tab Completions Error

### ISSUE THREAD

**Issue by Spear-Hwan** [SkQuery/SkQuery#81]
**Describe the bug**
Use 'Tab Completions' Expressions, the message "An internal error occurred while attempting to perform this command" is printed.

**Information:**
- Skript version: 2.5.3
- Server software: Paper
- Server version: 1.17.1

**Comment by TheLimeGlass** [comment]
Need the error

**Comment by TheLimeGlass** [comment]
Duplicate #14
