### ISSUE TITLE
Using On Any Move breaks On Teleport

### ISSUE THREAD

**Issue by oskarkk** [SkQuery/SkQuery#95]
**Describe the bug**

Using `on any move` prevents `on teleport` from ever firing. I've found this bug like two years ago, but couldn't find the exact cause. Maybe [this issue](https://github.com/SkriptLang/Skript/issues/396) is related.

**To Reproduce**

Run this script:

```
on any movement:

on teleport:
  message "works"
  log "works"
```

Try teleporting. You'll get no message. Disabling the script won't help, you must restart the server without the script enabled.

You can try the vanilla Skript event:

```
on player move:

on teleport:
  message "works"
  log "works"
```

This won't have the same effect, the teleport event will still work. I'm curious what is the root cause of this.

**Information:**
- Skript version: 2.6.1
- Server software: Paper
- Server version: 1.17.1

(I've had this bug for at least a year, so the versions aren't very important)

**Additional context**
I hope I helped someone with this, because I've just spent an hour disabling tens of scripts and plugins and restarting the server every time.

**Comment by TheLimeGlass** [comment]
You have the on player movement event empty in your provided example. You need to put code inside the event.

**Comment by oskarkk** [comment]
That doesn't change anything, I've tested it with various code in that event. I left it empty here for brevity.

**Comment by ImNotStable** [comment]
@TheLimeGlass 
I tested this with the latest Paper, SkQuery, and Skript version. There is no message
`
on any movement:
    send "test"

on teleport:
  message "works"
  log "works"
  cancel event
  `

I've tried with `on any movement:`  empty it persists.

**Comment by oskarkk** [comment]
@ImNotStable The cause is the Skript issue linked above: https://github.com/SkriptLang/Skript/issues/4705

Teleport event is a subclass of Movement event, and if Skript is listening to "parent" event it stops listening to child events. The same applies to events like `on portal`, `on move` etc. I'm closing this issue as it looks like it will be fixed in the next Skript release (and SkQuery couldn't do anything to fix it anyway).
